### ISSUE TITLE
Cannot find fftw3l when installing from pip

### ISSUE THREAD

**Issue by kusti8** [pyFFTW/pyFFTW#100]
So this is on a Raspberry Pi, and I ca't seem to get pyfftw installed. I suspect it has something to do with the recent move to NEON [discussed here](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=109584) on only the single precision version. 
```bash
pi@raspberrypi:~ $ sudo pip install pyfftw
Downloading/unpacking pyfftw
  Downloading pyFFTW-0.10.1.tar.gz (350kB): 350kB downloaded
  Running setup.py (path:/tmp/pip-build-cz5LII/pyfftw/setup.py) egg_info for package pyfftw
    
    warning: no files found matching '*.rst' under directory 'docs'
Installing collected packages: pyfftw
  Running setup.py install for pyfftw
    building 'pyfftw.pyfftw' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-cz5LII/pyfftw/include -I/tmp/pip-build-cz5LII/pyfftw/pyfftw -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c -o build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.o
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:268:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:268:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
     _import_array(void)
     ^
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:327:0,
                     from /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:269:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
     _import_umath(void)
     ^
    /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c: In function ‘__pyx_f_6pyfftw_6pyfftw_byte_align.isra.48.constprop’:
    /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:2763:6: warning: ‘__pyx_v_update_dtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (__pyx_t_1) {
          ^
    arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.o -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -o build/lib.linux-armv7l-2.7/pyfftw/pyfftw.so
    /usr/bin/ld: cannot find -lfftw3l
    /usr/bin/ld: cannot find -lfftw3l_threads
    collect2: error: ld returned 1 exit status
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-cz5LII/pyfftw/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iqzX37-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-armv7l-2.7

creating build/lib.linux-armv7l-2.7/pyfftw

copying pyfftw/__init__.py -> build/lib.linux-armv7l-2.7/pyfftw

copying pyfftw/version.py -> build/lib.linux-armv7l-2.7/pyfftw

creating build/lib.linux-armv7l-2.7/pyfftw/builders

copying pyfftw/builders/__init__.py -> build/lib.linux-armv7l-2.7/pyfftw/builders

copying pyfftw/builders/builders.py -> build/lib.linux-armv7l-2.7/pyfftw/builders

copying pyfftw/builders/_utils.py -> build/lib.linux-armv7l-2.7/pyfftw/builders

creating build/lib.linux-armv7l-2.7/pyfftw/interfaces

copying pyfftw/interfaces/__init__.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces

copying pyfftw/interfaces/cache.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces

copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces

copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces

copying pyfftw/interfaces/_utils.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces

running build_ext

building 'pyfftw.pyfftw' extension

creating build/temp.linux-armv7l-2.7

creating build/temp.linux-armv7l-2.7/tmp

creating build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII

creating build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII/pyfftw

creating build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII/pyfftw/pyfftw

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-cz5LII/pyfftw/include -I/tmp/pip-build-cz5LII/pyfftw/pyfftw -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c -o build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.o

In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,

                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,

                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,

                 from /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:268:

/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]

 #warning "Using deprecated NumPy API, disable it by " \

  ^

In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,

                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,

                 from /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:268:

/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]

 _import_array(void)

 ^

In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:327:0,

                 from /tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:269:

/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]

 _import_umath(void)

 ^

/tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c: In function ‘__pyx_f_6pyfftw_6pyfftw_byte_align.isra.48.constprop’:

/tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.c:2763:6: warning: ‘__pyx_v_update_dtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]

   if (__pyx_t_1) {

      ^

arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/tmp/pip-build-cz5LII/pyfftw/pyfftw/pyfftw.o -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -o build/lib.linux-armv7l-2.7/pyfftw/pyfftw.so

/usr/bin/ld: cannot find -lfftw3l

/usr/bin/ld: cannot find -lfftw3l_threads

collect2: error: ld returned 1 exit status

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-cz5LII/pyfftw/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iqzX37-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-cz5LII/pyfftw
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 98: ordinal not in range(128)
pi@raspberrypi:~ $ apt-cache search fftw3
cl-fftw3 - Common Lisp package for using the FFTW3 library
libfftw3-3 - Library for computing Fast Fourier Transforms
libfftw3-bin - Library for computing Fast Fourier Transforms - Tools
libfftw3-dbg - Library for computing Fast Fourier Transforms - debug symbols
libfftw3-dev - Library for computing Fast Fourier Transforms - development
libfftw3-doc - Documentation for fftw version 3
libfftw3-double3 - Library for computing Fast Fourier Transforms - Double precision
libfftw3-mpi-dev - MPI Library for computing Fast Fourier Transforms - development
libfftw3-mpi3 - MPI Library for computing Fast Fourier Transforms
libfftw3-single3 - Library for computing Fast Fourier Transforms - Single precision
pd-bsaylor - library of FFT-based Pd objects by Ben Saylor
python-fftw - Python bindings to the FFTW3 C-library for Fourier transforms
root-plugin-math-fftw3 - FFTw plugin for ROOT
ruby-fftw3 - Ruby interface to the FFTW Ver.3 library
ruby-fftw3-dbg - Ruby FFT library using FFTW Ver.3
pi@raspberrypi:~ $ ls /usr/include/fftw*
/usr/include/fftw3.f         /usr/include/fftw3-mpi.h
/usr/include/fftw3.f03       /usr/include/fftw3q.f03
/usr/include/fftw3.h         /usr/include/fftw.h
/usr/include/fftw3l.f03      /usr/include/fftw_mpi.h
/usr/include/fftw3l-mpi.f03  /usr/include/fftw_threads.h
/usr/include/fftw3-mpi.f03
pi@raspberrypi:~ $ apt-cache policy libfftw3-3
libfftw3-3:
  Installed: 3.3.4-2+rvt
  Candidate: 3.3.4-2+rvt
  Version table:
 *** 3.3.4-2+rvt 0
        500 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
pi@raspberrypi:~ $ 
```

**Comment by hgomersall** [comment]
Interesting. I've no experience trying this on ARM. Do you have `libfftw3l.so` somewhere (which is what the linker needs)?

**Comment by kusti8** [comment]
Well, my Pi just crashed because I ran out of space so I'm reinstalling it and will let you know if `libfftw3l.so` is anywhere.

**Comment by kusti8** [comment]
Nothing. 
```
pi@raspberrypi:~ $ sudo find / -name libfftw3l*
pi@raspberrypi:~ $
```

**Comment by kusti8** [comment]
Got it! I built it manually with the patch described [here](http://www.eliteraspberries.com/blog/2013/10/building-a-numerical-python-environment-in-debian.html) and now it works. Closing, but there should be a fix to get it to cleanly build without a patch.

**Comment by hgomersall** [comment]
PRs gratefully received.

**Comment by kusti8** [comment]
I don't know enough about FFTO to make a PR that actually works and does not interfere with anything else, but this does seem to be related to this issue: https://github.com/pyFFTW/pyFFTW/issues/70

**Comment by davelawr** [comment]
Hi,
what was the solution to this? the link to the patch has disappeared.
Thanks,

**Comment by davelawr** [comment]
Hi Gregory, thank you for your quick reply.

As per the original post in this thread I am trying to build pyFFTW on a raspberry pi. I'm using the standard raspbian stretch image.

I have just tried your suggestion of building from the master.zip and it looks as if it successfully detected the various 'sizes', but has now thrown a different error:

Here's the complete output:

```
Collecting numpy<2.0,>=1.10 (from pyFFTW==0+unknown)
  Using cached https://files.pythonhosted.org/packages/3a/20/c81632328b1a4e1db65f45c0a1350a9c5341fd4bbb8ea66cdd98da56fe2e/numpy-1.15.0.zip
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /home/pi/.cache/pip/wheels/77/d2/00/03180c22fc40b6f17f6a5c6ea0fa1689734a9cf4cf54179a1c
Successfully built numpy
Installing collected packages: numpy, pyFFTW
  Running setup.py install for pyFFTW ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-xC6svc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pXsIeX-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/pyfftw
    copying pyfftw/__init__.py -> build/lib.linux-armv7l-2.7/pyfftw
    copying pyfftw/_version.py -> build/lib.linux-armv7l-2.7/pyfftw
    creating build/lib.linux-armv7l-2.7/pyfftw/builders
    copying pyfftw/builders/builders.py -> build/lib.linux-armv7l-2.7/pyfftw/builders
    copying pyfftw/builders/__init__.py -> build/lib.linux-armv7l-2.7/pyfftw/builders
    copying pyfftw/builders/_utils.py -> build/lib.linux-armv7l-2.7/pyfftw/builders
    creating build/lib.linux-armv7l-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/dask_fft.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/cache.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/__init__.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/_utils.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-armv7l-2.7/pyfftw/interfaces
    UPDATING build/lib.linux-armv7l-2.7/pyfftw/_version.py
    set build/lib.linux-armv7l-2.7/pyfftw/_version.py to '0+unknown'
    running build_ext
    Build pyFFTW with support for FFTW with
    double precision + openMP
    single precision + openMP
    building 'pyfftw.pyfftw' extension
    error: unknown file type '.pyx' (from '/tmp/pip-xC6svc-build/pyfftw/pyfftw.pyx')
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-xC6svc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pXsIeX-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-xC6svc-build/
```

br,

**Comment by grlee77** [comment]
Do you have cython installed?

**Comment by davelawr** [comment]
Ah! no... That's fixed it. Thank you

**Comment by grlee77** [comment]
Great! We don't yet do testing on ARM, so please report any issues you may encounter.

We can work on making pip know that it needs to install Cython first prior to trying to install PyFFTW. I think the addition of `pyproject.toml` file as originally proposed in #204 would have caused pip to install Cython first for you, but as far as I know there is a bug in current pip that has caused us to hold off on including that file for the moment.

**Comment by davelawr** [comment]
Hi, fyi: I'm using this with https://github.com/xmikos/qspectrumanalyzer
