### ISSUE TITLE
Builders and axes

### ISSUE THREAD

**Issue by davidbrough1** [pyFFTW/pyFFTW#106]
The following code runs with pyfftw 0.9.2 and 0.10.1 without a problem

    import numpy as np
    from pyfftw import builders

    X = np.ones((1, 33, 33, 2))

    FX = builders.rfftn(X, axes=[1, 2, 3])

but if the `axes` argument is changed 

    import numpy as np
    from pyfftw import builders
 
    X = np.ones((1, 33, 33, 2))

    FX = builders.rfftn(X, axes=[1, 2])

a  `RuntimeError` is raised

    Traceback (most recent call last):
      File "pyfftw_issues.py", line 6, in <module>
        FX = builders.rfftn(X, axes=[1, 2])
      File "/home/david/anaconda2/envs/pymks_dev_fftw/lib/python2.7/site-packages/pyfftw/builders/builders.py", line 471, in rfftn
        avoid_copy, inverse, real)
      File "/home/david/anaconda2/envs/pymks_dev_fftw/lib/python2.7/site-packages/pyfftw/builders/_utils.py", line 169, in _Xfftn
        flags, threads)
      File "pyfftw.pyx", line 971, in pyfftw.pyfftw.FFTW.__cinit__ (pyfftw/pyfftw.c:7658)
    RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.

**Comment by grlee77** [comment]
Do you by any chance also have MKL installed? (e.g. using anaconda with the default numpy/scipy)  If so, this is likely another case of #40

(For your particular example above, the MKL FFT routines don't support transforms where the number of axes to be transformed are more than 1 fewer than the number of array dimensions)

**Comment by hgomersall** [comment]
Yeah, it looks like that - I certainly can't reproduce it. I suggest following the workarounds in #40 and if that's the case, go and bug Anaconda about it.

**Comment by davidbrough1** [comment]
It looks like it might be a case similar to #40.

For what it's worth, when using a version of anaconda <=2.4.1 with MKL I don't get this error regardless of the order of import statements. If I use a version of anaconda >2.4.1 with MKL I have to have the import statements in the following order to not get the error.

     from pyfftw import builders
     import numpy as np

**Comment by ferdinandvanwyk** [comment]
Just started seeing this error on Travis CI since I use Miniconda to handle packages which may require compilation. So others don't have to follow a trail of issues, in addition to the above solutions you can simply disable MKL optimizations if you don't need them in Anaconda/Miniconda via:

```bash
$ conda install nomkl
```

[Source](https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations)

**Comment by hgomersall** [comment]
@ferdinandvanwyk Any ideas why this is not a problem currently for pyfftw? We also use miniconda.

**Comment by ferdinandvanwyk** [comment]
@hgomersall As @grlee77 pointed out: 

> MKL FFT routines don't support transforms where the number of axes to be transformed are more than 1 fewer than the number of array dimensions

My test cases involve arrays which have one dimension representing time which I iterate over and don't want to FFT, leading to the above.

Do you have any tests like that? Had a quick look but you might know off hand.

**Comment by grlee77** [comment]
As far as I could tell there are not tests of N dimensional transforms where the number of axes transformed are fewer than N-1.

See the explict numpy fftn interface test shapes here:
https://github.com/pyFFTW/pyFFTW/blob/a5be2182046e18f6f2d06d9becb3b00c138b1821/test/test_pyfftw_numpy_interface.py#L725-L733

It should only be a couple lines modified to add a case there with 3D data and only 1 axis transformed or 4D data with 2 axes transformed.  @ferdinandvanwyk or @davidbrough1 :  are either of you interested in making a PR for this? probably worth adding that case to the `builders` tests as well

**Comment by sambarluc** [comment]
I see this issue also on my miniconda installation, using python 3.
I wanted to add that the solution in https://github.com/pyFFTW/pyFFTW/issues/40 that is installing from conda-forge, does work. However, the precompiled pyfftw is actually slower than numpy.fft using MKL.

**Comment by hgomersall** [comment]
@sambarluc how much slower? What were you doing to test that? Is it using interfaces?

**Comment by sambarluc** [comment]
@hgomersall  yes, sorry, I didn't think anyone would actually be reading.

The installation (os Linux 4.4.0-92, Ubuntu):
- from conda (miniconda):

> numpy                     1.13.1                   py36_0  
> python                    3.6.2                         0  
> mkl                       2017.0.3                      0  

- pyFFTW compiled via pip:

> pyFFTW (0.10.4)

  pyFFTW installed from conda-forge:

> pyfftw                    0.10.4              np113py36_1    conda-forge


Timings:
- Numpy (with mkl)
```
In [1]: import numpy as np
In [2]: x=np.random.random(4096)
In [3]: %timeit np.fft.fft(x)
79.1 µs ± 661 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
- Locally compiled pyFFTW from pip, works great:
```
In [6]: import pyfftw
In [7]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [8]: a[:] = x
In [9]: fftobj = pyfftw.builders.fft(a)
In [10]: %timeit fftobj()
15.4 µs ± 443 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
BTW, it speeds up substantially also with interfaces, and I didn't even switch on the cache.
- conda-forge pyFFTW
```
In [1]: import numpy as np
In [2]: import pyfftw
In [3]: x=np.random.random(4096)
In [4]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [5]: a[:] = x
In [6]: fftobj = pyfftw.builders.fft(a)
In [7]: %timeit fftobj()
110 µs ± 202 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [8]: %timeit np.fft.fft(x)
77.9 µs ± 73.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

So, at the moment, I am actually using pyFFTW from pip (locally compiled), and use it for 1D transforms (or 2D over 2 axes, etc), whereas I use numpy.fft for other transforms.

**Comment by hgomersall** [comment]
Hmm, that looks suspicious. Why such a slow down? Is it using the MKL library? Try using it with transforms the MKL doesn't support and see if it whinges? Or try reordering the import (so pyfftw before numpy).

**Comment by sambarluc** [comment]
Reordering:
```
In [1]: import pyfftw
In [2]: import numpy as np
In [3]: x=np.random.random(4096)
In [4]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [5]: a[:] = x
In [6]: fftobj = pyfftw.builders.fft(a)
In [7]: %timeit fftobj()
111 µs ± 427 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

MKL unsupported transform:
```
In [9]: shape = (100, 1, 4096)
In [10]: x=np.random.random(np.prod(shape)).reshape(shape)
In [11]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [12]: a[:] = x
In [13]: %timeit np.fft.fft(x)
7.87 ms ± 9.75 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [14]: fftobj = pyfftw.builders.fft(a)
In [15]: %timeit fftobj()
11.3 ms ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by sambarluc** [comment]
Sorry, I slipped 2 zeros too much in my shape, but results are consistent:

```
In [1]: import pyfftw
In [2]: import numpy as np
In [3]: shape = (1, 1, 4096)
In [4]: x=np.random.random(np.prod(shape)).reshape(shape)
In [5]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [6]: a[:] = x
In [7]: fftobj = pyfftw.builders.fft(a)
In [9]: %timeit fftobj()
116 µs ± 5.72 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [10]: %timeit np.fft.fft(x)
78 µs ± 730 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by hgomersall** [comment]
@sambarluc I've no idea! Something odd is happening. I'd be very keen to help you work through this and understand it better, so please do! I think you should raise this as another issue because it doesn't seem very relevant to the original issue.

**Comment by sambarluc** [comment]
No doubt it's odd! I'll open a new issue.
Thanks for your feedback.

**Comment by jakirkham** [comment]
Was this resolved in issue ( https://github.com/pyFFTW/pyFFTW/issues/184 )? Looks like it might have been.

**Comment by jacobjma** [comment]
I believe this issue has been reintroduced with version 0.13.0.

To reproduce I install Numpy (1.21.2) and pyfftw (0.13.0) in a fresh conda env like this
```
conda install numpy
conda install -c conda-forge pyfftw
```
then I run the following code
```
import numpy as np
import pyfftw
x = np.zeros((5,5,5,5))
fftw_obj = pyfftw.builders.ifft2(x)
```
which raises the RuntimeError:
```
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.
```

The error does not occur when using pyfftw-0.12.0. It also does not occur when using Numpy without mkl or when pyfftw is imported before Numpy.

I tested this using Ubuntu with WSL.

**Comment by hgomersall** [comment]
Interactions with MKL I feel are beyond the remit of the project. Given that MKL explicitly treads on the same symbols as FFTW, the fact it works at all is kind of impressive. How do you propose we deal with this?

**Comment by hgomersall** [comment]
Unless it's related to #184 again.

**Comment by jacobjma** [comment]
I don't know enough about this to comment on a solution. Other than to reintroduce the static linking that was removed in 0.13.0 (https://github.com/conda-forge/pyfftw-feedstock/pull/47#issuecomment-1001815019).

**Comment by grlee77** [comment]
Okay, thanks for reporting the issue. I can reintroduce the static linking in the conda-forge recipe.

**Comment by jakirkham** [comment]
@jacobjma, why does the `conda install numpy` command not also specify `conda-forge`? It sounds like this would mix packages from different channels, which may be causing the issue

**Comment by grlee77** [comment]
@jacobjma, there should be a new build of v0.13.0 up on conda-forge now that has the static linking again (build 1). 

I think this type of static linking is generally discouraged by conda-forge, but in this case we did have it for a specific reason. It may not be necessary when using the conda-forge `numpy` packages, though?

**Comment by jakirkham** [comment]
Right `defaults` builds `numpy` with MKL only, which would enable using MKL with FFT support in NumPy. As MKL uses the same symbol names as FFTW, these clash when both libraries are loaded in the same process. Hence why static linking helps in this case.

However conda-forge builds against a generic BLAS & LAPACK (NETLIB), but then allows users to use different BLAS & LAPACK implementations (like MKL or OpenBLAS) at runtime. The result is NumPy in conda-forge uses NumPy's own included FFT implementation (currently pocketfft IIRC). So there is no symbol clashing.

**Comment by jacobjma** [comment]
@jakirkham You are right, I should not assume that mixing channels should work. 

@grlee77 Thank you for the swift resolution! I tested the new build and it works great. This is resolved as far as I am concerned.

To answer yours and @jakirkham questions, the conda-forge version of numpy does not use MKL and hence it should work fine with the previous build of pyFFTW-0.13.0. However, it is very likely that users of my code are going to mix channels, and hence it is really nice that pyFFTW is able to work with MKL.

I understand why static linking is discouraged, but I think there is a good reason to keep it in this case.

**Comment by jakirkham** [comment]
Thanks for following up Jacob!

When it comes to using conda-forge, users are advised to [add `conda-forge` to their config and set strict channel priority]( https://conda-forge.org/docs/user/introduction.html?highlight=strict#how-can-i-install-packages-from-conda-forge ). This should minimize these channel mixing issues.
