### ISSUE TITLE
pyfftw.FFTW needs a function __getnewargs__ for pickle

### ISSUE THREAD

**Issue by paugier** [pyFFTW/pyFFTW#130]
In order to use pyfftw.FFTW with multiprocessing on Windows, the fft plans have to be pickled and unpickled.

Now unpickling a plan leads to an error:

```
Traceback (most recent call last):
  File "bug_pyfftw_pickle.py", line 31, in <module>
    fftplan = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
  File "pyfftw.pyx", line 694, in pyfftw.pyfftw.FFTW.__cinit__ (/tmp/pip_build_root/pyfftw/pyfftw/pyfftw.c:4929)
TypeError: __cinit__() takes at least 2 positional arguments (0 given)

```

It may be possible to solve this issue simply by adding a function `__getnewargs__` to the class in the pyx file.

Simple example showing the issue and the idea to solve it:
```
import pickle

import pyfftw

ny = nx = 8
shapeX = [ny, nx]
shapeK = [ny, nx//2 + 1]
arrayX = pyfftw.n_byte_align_empty(shapeX, 16, 'float32')
arrayK = pyfftw.n_byte_align_empty(shapeK, 16, 'complex64')

error = True

if error:
    FFTW = pyfftw.FFTW
else:
    class FFTW(pyfftw.FFTW):
        def __getnewargs__(self):
            print('__getnewargs__')
            return (self.get_input_array(), self.get_output_array())
    
fftplan = FFTW(
    input_array=arrayX, output_array=arrayK,
    axes=(0, 1), direction='FFTW_FORWARD')

name = 'tmp.pickle'

with open(name, 'wb') as f:
    pickle.dump(fftplan, f, pickle.HIGHEST_PROTOCOL)
        
with open(name, 'rb') as f:
    fftplan = pickle.load(f)

```

**Comment by hgomersall** [comment]
Oh, interesting. I hadn't noted this issue. This should be quite easy to implement (along with a suitable test). Fancy a bash?

**Comment by paugier** [comment]
If I remember well, this impossibility to pickle an fft plan was a problem to use pyfftw with multiprocessing on Windows. 

I don't know if it is still a problem with a recent Python version. I don't have an easy way to check on Windows so I can't say for sure.

Anyway, I think allowing multiprocessing+pyfftw on Windows would be useful.

**Comment by hgomersall** [comment]
I have no need for it, but I can see why it might be useful. As before, happy for a pull request that implements this stuff.

**Comment by grizonnetm** [comment]
I  would be also interested to be able to be able to use pyfftw plans with multiprocessing but I know nothing about pickle and cython :(

I've started to read pickle documentation and it seems that instead of implementing ``__reduce__`` method it is possible to implement a set of methods (including ``__getnewargs__``):

> Although powerful, implementing __reduce__() directly in your classes is error prone. For this reason, class designers should > use the high-level interface (i.e., __getnewargs_ex__(), __getstate__() and __setstate__()) whenever possible. We will show, > however, cases where using __reduce__() is the only option or leads to more efficient pickling or both.

Find it at: https://docs.python.org/3/library/pickle.html#object.__reduce__

I would be happy to help on this.
