### ISSUE TITLE
Error while installing with pip 

### ISSUE THREAD

**Issue by maciekgroch** [pyFFTW/pyFFTW#168]
Hey, 

I was trying to install pyFFTW on a windows machine using Anaconda 3.5. What I get while simply executing `pip install pyfftw` is:
```
  ----------------------------------------
  Failed building wheel for pyfftw
  Running setup.py clean for pyfftw
Failed to build pyfftw
Installing collected packages: pyfftw
  Running setup.py install for pyfftw ... error
    Complete output from command C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\M29EC~1.GRO\\AppData\\Local\\Temp\\pip-build-0qgx68a0\\pyfftw\\setup.py
';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\M29EC~1.GRO\AppData\Local\Temp\pip-caml0y7t-record\install-record.txt
--single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    running install_lib
    creating C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw
    creating C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders
    copying build\lib.win-amd64-3.6\pyfftw\builders\builders.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders
    copying build\lib.win-amd64-3.6\pyfftw\builders\_utils.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders
    copying build\lib.win-amd64-3.6\pyfftw\builders\__init__.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders
    creating C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces
    copying build\lib.win-amd64-3.6\pyfftw\interfaces\cache.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces
    copying build\lib.win-amd64-3.6\pyfftw\interfaces\numpy_fft.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces
    copying build\lib.win-amd64-3.6\pyfftw\interfaces\scipy_fftpack.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces
    copying build\lib.win-amd64-3.6\pyfftw\interfaces\_utils.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces
    copying build\lib.win-amd64-3.6\pyfftw\interfaces\__init__.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces
    copying build\lib.win-amd64-3.6\pyfftw\pyfftw.cp36-win_amd64.pyd -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw
    copying build\lib.win-amd64-3.6\pyfftw\version.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw
    copying build\lib.win-amd64-3.6\pyfftw\__init__.py -> C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders\builders.py to builders.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders\_utils.py to _utils.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\builders\__init__.py to __init__.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces\cache.py to cache.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces\numpy_fft.py to numpy_fft.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces\scipy_fftpack.py to scipy_fftpack.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces\_utils.py to _utils.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\interfaces\__init__.py to __init__.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\version.py to version.cpython-36.pyc
    byte-compiling C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\Lib\site-packages\pyfftw\__init__.py to __init__.cpython-36.pyc
    running install_egg_info
    running egg_info
    writing pyFFTW.egg-info\PKG-INFO
    writing dependency_links to pyFFTW.egg-info\dependency_links.txt
    writing top-level names to pyFFTW.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pyFFTW.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\M29EC~1.GRO\AppData\Local\Temp\pip-build-0qgx68a0\pyfftw\setup.py", line 492, in <module>
        setup_package()
      File "C:\Users\M29EC~1.GRO\AppData\Local\Temp\pip-build-0qgx68a0\pyfftw\setup.py", line 489, in setup_package
        setup(**setup_args)
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install_egg_info.py", line 35, in run
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 195, in run
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 222, in find_sources
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 306, in run
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 342, in add_defaults
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\sdist.py", line 234, in read_manifest
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 247, in append
      File "C:\Users\m.grochowicz\AppData\Local\Continuum\Anaconda3\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/whg/Projects/github/pyFFTW/pyfftw/pyfftw.c' cannot be absolute

```

I have all the dependencies installed, and the traceback suggests that the issue is in:
```
      File "C:\Users\M29EC~1.GRO\AppData\Local\Temp\pip-build-0qgx68a0\pyfftw\setup.py", line 492, in <module>
        setup_package()
      File "C:\Users\M29EC~1.GRO\AppData\Local\Temp\pip-build-0qgx68a0\pyfftw\setup.py", line 489, in setup_package
        setup(**setup_args)
```

I hope I am not missing something and wasting your time :).
Thank you for help.

**Comment by grlee77** [comment]
I think the error is the statement `Failed to build pyfftw` near the top of the log you posted.  You would need to run pip in verbose mode to see where in the build things went wrong.  You can do this via `pip install pyfftw -v`.  You could also add `--log logfile.txt` to have pip save a verbose log.

Most likely the problem is that building pyFFTW requires compilation of C (Cython) code and getting the compiler set up right can be a bit of a pain on Windows.  The easiest workaround is probably to use a pre-built wheel from here:  http://www.lfd.uci.edu/~gohlke/pythonlibs/

assuming you are on 64-bit windows you want the one labeled: `pyFFTW‑0.10.4‑cp35‑cp35m‑win_amd64.whl`

you install it after downloading via:
`pip install pyFFTW‑0.10.4‑cp35‑cp35m‑win_amd64.whl`

**Comment by miromarszal** [comment]
Same issue here on Windows 10. The log is attached: [logfile.txt](https://github.com/pyFFTW/pyFFTW/files/1070758/logfile.txt)

**Comment by hgomersall** [comment]
Is it with Python 3.5? It looks like it's not from your log file - pip is skipping all the windows wheels.

**Comment by hgomersall** [comment]
I don't understand why people are having issues on windows. The pre-built binaries are much easier to use than trying to build it oneself. If you need versions for Python 3.6, then head over to [bintray](https://bintray.com/hgomersall/generic/PyFFTW-development-builds/0.10.5#files).

**Comment by miromarszal** [comment]
> Is it with Python 3.5? It looks like it's not from your log file

It's my log file and it's Python 3.6. Now I see what's the problem ;)

> I don't understand why people are having issues on windows.

Let me explain. An inexperienced user (like me) will think that `pip install pyfftw` will do the job and honestly I think that the major point of pip is exactly that. The error message is not very informative hence the issues.
