### ISSUE TITLE
Another undefined symbol

### ISSUE THREAD

**Issue by josefkorbel** [pyFFTW/pyFFTW#203]
Hello, 
After serious struggle I am thinking about giving up. What I want to achieve is to install pyFFTW on raspberry pi (Raspberry compute module to be precise)

First i tried to only `pip install pyfftw` , that gave me error which clearly indicates that there is no c lang compiler. Okay. I installed `gcc` and proceed further. After some googling I found out that i need to install all precision versions of FFTW manually, so I did. After that, i was finaly able to install pyFFTW with `pip install pyfftw`.

However when i try to import it with `python -c "import pyfftw"` i get and error.
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import pyfftw
  File "/usr/local/lib/python2.7/dist-packages/pyfftw/__init__.py", line 16, in <module>
    from .pyfftw import (
ImportError: /usr/local/lib/libfftw3l_threads.so.3: undefined symbol: fftwl_dft_solve
```
Okay i though that the .so file is missing the `fftwl_dft_solve` so i tried to look at it.
`> nm -D /usr/local/lib/libfftw3l_threads.so.3 | grep fftwl_dft_solve` 
This returns: `U fftwl_dft_solve` 
so clearly it is not the cause.

Strange, so i tried to `ldd` the file.

`> ldd -d -r /usr/local/lib/libfftw3l_threads.so.3`
```
linux-vdso.so.1 (0x7ee2d000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f82000)
        libfftw3l.so.3 => /usr/local/lib/libfftw3l.so.3 (0x76ec3000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76e48000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76e20000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76cdf000)
        /lib/ld-linux-armhf.so.3 (0x76fac000)
undefined symbol: fftwl_dft_solve       (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_rdft_solve      (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_rdft2_solve     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mksolver_hc2hc_hook     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mksolver_ct_hook        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_malloc_plain    (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mktensor_1d     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_set_planner_hooks       (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_rdft2_inplace_strides   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_tensor_copy     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_solvtab_exec    (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_rdft2_strides   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_cleanup (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_pickdim (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_assertion_failed        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkplan_rdft     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_tensor_tornk1   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_ops_add2        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_solver_register (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_plan_destroy_internal   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkplan_dft      (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkplan_d        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mktensor_2d     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkplan_rdft2    (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkproblem_dft_d (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_tensor_destroy  (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_ops_zero        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_ifree   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_imax    (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkproblem_rdft_d        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_hc2hc_applicable        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_ct_applicable   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mksolver        (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkproblem_rdft  (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_the_planner     (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkproblem_rdft2 (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_mkproblem_dft   (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_plan_awake      (/usr/local/lib/libfftw3l_threads.so.3)
undefined symbol: fftwl_choose_radix    (/usr/local/lib/libfftw3l_threads.so.3)
```

So it is not only the `fftwl_dft_solve` which i got in the error message, it was just the first one to fail.
But libggtw3l.so is the only module with path that does not contain `arm-linux-gnueabihf`, AHA.

I found one more thing in the issues, and that was to check `pkg-config` if it imported dynamically all three version properly.
`> pkg-config --libs fftw3`
`-L/usr/local/lib -lfftw3` so i changed that in the `.rc` file to `-L/usr/local/lib -lfftw3, -lfftw3_threads`

But guess what, still the same error is appearing when im trying to import pyfftw, I feel like sherlock holmes but still the error seems far from me, any tips?

**Comment by hgomersall** [comment]
Don't use pip for this. You might have a hope if you use master. There has been quite a bit of recent work in supporting different systems. Take a look at #189 and #201 which are likely applicable here.

The problem is we've only recently started taking a serious look supporting ARM and missing versions. We're close, but it might still need a bit of playing on your part.

Happy to advise and keen to see it working, but I suggest you have a bash with the most recent code.

**Comment by josefkorbel** [comment]
Hello,

So i downloaded master directly and installed it using `sudo python setup.py build_ext --inplace`

It is still not working though, however, the error is different.

`> python -c "import pyfftw"`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyfftw/__init__.py", line 14, in <module>
    from .pyfftw import (
ImportError: pyfftw/pyfftw.so: undefined symbol: fftwl_plan_with_nthreads
```

`> nm -D /usr/local/lib/libfftw3l_threads.so | grep fftwl_plan_with_nthreads`
returns `00001688 T fftwl_plan_with_nthreads`

**Comment by hgomersall** [comment]
I think you're going to have to pull those changes in the new PRs and try again and probably dig a bit yourself. At some point (hopefully in the not too distant future), I'll get FFTW on an RPi working properly.

Your digging is valued, but I don't have too much time to put to it myself at the moment.

**Comment by josefkorbel** [comment]
Okay that seems promising,

I cloned master to dir.
`git clone https://github.com/pyFFTW/pyFFTW/`

Applied PR #189 
`git fetch origin pull/189/head:PRTEST`
`git checkout PRTEST`

`sudo python -c "import pyfftw"` now proceed without any error, so I hope it is all working now, I'll try it in action shortly to be sure, thank you for your valuable tips @hgomersall !

Cheers

**Comment by josefkorbel** [comment]
EDIT: It really works, thanks.

**Comment by grlee77** [comment]
Great!  We also attempt to detect ARM and set an appropriate memory alignment in #201, but haven't yet tested it on actual ARM hardware.  If you do end up trying a build with that PR incorporated, can you please report what value is returned for `pyfftw.simd_alignment`?  Would also be good to verify that the test suite passes.  #201 should result in an appropriate alignment if you have built FFTW with NEON instruction set support.

**Comment by josefkorbel** [comment]
Of course, but I am leaving the office already, will look into it tomorrow :)

**Comment by jakirkham** [comment]
Anything else to do here or is this good to close?
