### ISSUE TITLE
Adding code coverage for base + mpi branch

### ISSUE THREAD

**Issue by s-sajid-ali** [pyFFTW/pyFFTW#235]
I was able to automate the build of the mpi branch and add code coverage to the python files. I've been unable to do the same for the cython code. Could someone help me with the same ?  

[Here](https://github.com/s-sajid-ali/pyFFTW/tree/mpi-pr-new) is the branch in which I've built upon @fredRos's mpi branch. The travis builds are [here](https://travis-ci.com/s-sajid-ali/pyFFTW/builds).  I've used [spack](https://github.com/spack/spack/) to build and mpich load fftw (linked to mpich). The codecov reports are [here](https://codecov.io/gh/s-sajid-ali/pyFFTW/branch/mpi-pr-new). They worked until I didn't touch the cython files. 

I then followed [this advice](http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html) to get the codecov results for the cython code and now I get this error `Fatal Python error: PyThreadState_Get: no current thread`. I've tried to search for what this means and all I've found out is that this is caused by multiple versions of python as per [[1](https://github.com/caffe2/caffe2/issues/854#issuecomment-320865933)] though I don't see how this is happening in the travis build. 

I think this might be caused by the fact that I'm passing a `disutils` flag to the build while the build is using `setuptools`. In that case, there's this advice [here](https://medium.com/@dfdeshom/better-test-coverage-workflow-for-cython-modules-631615eb197a) which I tried to follow but I didn't see a cythonize in the `setup.py`. I'm unsure as to how the compiler directives are to be added. Could someone guide me here ?

**Comment by hgomersall** [comment]
I'm confused, is this pertinent to the main branch? Code coverage analysis is great - do you have a version that is applicable to master?

**Comment by s-sajid-ali** [comment]
It works for the `.py` files but I was unable to profile the cython files. As this [coverage report](https://codecov.io/gh/s-sajid-ali/pyFFTW/branch/mpi-pr-new) shows, all coverage for all  the `.py` files is present. The task now is to extend the same to the cython files.

**Comment by hgomersall** [comment]
Yeah, I tried at one point to do code coverage and ran into the same problems. If you're able to work through this, it would be gratefully received. Obviously, code coverage without cython is pretty useless (since that's kinda central to it's functionality!).

**Comment by s-sajid-ali** [comment]
I'll switch the travis config to test base branch with all the scripts and see if we can figure something out from there. I was also confused with the build system but I'll post a more specific error soon.

**Comment by jakirkham** [comment]
If you have any luck getting code coverage from Cython, would be interested to learn from you. Had tried on a simple module and couldn't get anywhere so raised issue ( https://github.com/cython/cython/issues/1985 ).

**Comment by s-sajid-ali** [comment]
@jakirkham @hgomersall 

I have a working demonstration for cython source file coverage [[here ](https://github.com/s-sajid-ali/cython_test_coverage)]. Travis builds are [[here](https://travis-ci.com/s-sajid-ali/cython_test_coverage)] and Codecov reports are [[here](https://codecov.io/gh/s-sajid-ali/cython_test_coverage)]. As can be seen, the `basic_cython.pyx` file is being tested for coverage. 

I tried doing the same with `pyFFTW` repo and ran into some issues [[1](https://travis-ci.com/s-sajid-ali/pyFFTW)]. For some reason, cython won't annotate the main source file due to compile time names being not defined. Does any of you have any clue as to why this happens ?

**Comment by grlee77** [comment]
There are quite a few names that get defined dynamically within `setup.py` for use via `cython_compile_time_env`. These indicate which precisions and threading types are available on the machine. Most likely you have to also specify a value for each of these in the command line case when running coverage.

The full list of these and their values on my system (it gets printed near the end of the verbose output of `python setup.py -v build_ext `):

{'HAVE_DOUBLE': True, 'HAVE_DOUBLE_OMP': True, 'HAVE_DOUBLE_THREADS': False, 'HAVE_DOUBLE_MULTITHREADING': True, 'HAVE_DOUBLE_MPI': False, 'HAVE_SINGLE': True, 'HAVE_SINGLE_OMP': True, 'HAVE_SINGLE_THREADS': False, 'HAVE_SINGLE_MULTITHREADING': True, 'HAVE_SINGLE_MPI': False, 'HAVE_LONG': True, 'HAVE_LONG_OMP': True, 'HAVE_LONG_THREADS': False, 'HAVE_LONG_MULTITHREADING': True, 'HAVE_LONG_MPI': False, 'HAVE_MPI': False}

According to `cython -h` it looks like you should be able to pass values for all of these to cython at the command line via `--compile-time-env name=value[,<name=value,...]` .

**Comment by s-sajid-ali** [comment]
@grlee77 : Thanks for pointing that out. 

I've fixed that and now I see a confusing [error on TravisCI ](https://travis-ci.com/s-sajid-ali/pyFFTW/jobs/230261086): 
```
 coverage run test/test_pyfftw_base.py
Traceback (most recent call last):
  File "test/test_pyfftw_base.py", line 35, in <module>
    from pyfftw import FFTW, _supported_types, _all_types_human_readable
ModuleNotFoundError: No module named 'pyfftw'
The command "coverage run test/test_pyfftw_base.py" failed and exited with 1 during .
```

`pyFFTW` was built and installed (lines 579,729) but an import error still occurs.

**Comment by s-sajid-ali** [comment]
I rebased everything onto master at https://github.com/s-sajid-ali/pyFFTW/commit/0a410dfbbe9baca269fe9bf95c4aea9382f28382 and while the library compiles and tests run, the test suite crashes upon completion : [travis output](https://travis-ci.com/github/s-sajid-ali/pyFFTW/jobs/326117372).

The exact error is  :
```
Ran 492 tests in 87.200s

OK
Fatal Python error: PyThreadState_Get: no current thread

Traceback (most recent call last):
  File "setup.py", line 811, in <module>
    setup_package()
  File "setup.py", line 808, in setup_package
    setup(**setup_args)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 731, in run
    'unittest'] + quick_test_cases)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/travis/miniconda/envs/test-environment/bin/python', '-m', 'unittest', 'test.test_pyfftw_complex.Complex64FFTWTest', 'test.test_pyfftw_complex.Complex128FFTWTest.test_2d', 'test.test_pyfftw_complex.ComplexLongDoubleFFTWTest.test_2d', 'test.test_pyfftw_real_forward.RealForwardSingleFFTWTest', 'test.test_pyfftw_real_forward.RealForwardDoubleFFTWTest.test_2d', 'test.test_pyfftw_real_forward.RealForwardLongDoubleFFTWTest.test_2d', 'test.test_pyfftw_real_backward.RealBackwardSingleFFTWTest', 'test.test_pyfftw_real_backward.RealBackwardDoubleFFTWTest.test_2d', 'test.test_pyfftw_real_backward.RealBackwardLongDoubleFFTWTest.test_2d', 'test.test_pyfftw_wisdom', 'test.test_pyfftw_utils', 'test.test_pyfftw_call', 'test.test_pyfftw_class_misc', 'test.test_pyfftw_nbyte_align', 'test.test_pyfftw_interfaces_cache', 'test.test_pyfftw_multithreaded', 'test.test_pyfftw_numpy_interface.InterfacesNumpyFFTTestModule', 'test.test_pyfftw_numpy_interface.InterfacesNumpyFFTTestFFT2', 'test.test_pyfftw_numpy_interface.InterfacesNumpyFFTTestIFFT2', 'test.test_pyfftw_builders.BuildersTestFFTWWrapper', 'test.test_pyfftw_builders.BuildersTestFFT2', 'test.test_pyfftw_builders.BuildersTestIRFFT2']' died with <Signals.SIGABRT: 6>
```

As per my internet search, I think this error is caused by having multiple installations of python conflict at runtime but given that the traceback shows that the correct python executable is being run, I'm not sure as to why it aborts. Any clue as to what could cause this ?
