### ISSUE TITLE
futurewarnings in dask 2.8 break test suite

### ISSUE THREAD

**Issue by xnox** [pyFFTW/pyFFTW#276]
please add dask 2.8 compat

seems like only the test suite is affected.

I had to ignore futurewarnings coming from dask, but I guess that's only a temporary solution.

**Comment by xnox** [comment]
```
======================================================================
FAIL: test_shape_and_s_different_lengths (test.test_pyfftw_dask_interface.InterfacesDaskFFTTestFFTN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pyFFTW/pyFFTW/test/test_pyfftw_dask_interface.py", line 525, in test_shape_and_s_different_lengths
    test_shape, dtype, s, kwargs)
  File "/home/travis/build/pyFFTW/pyFFTW/test/test_pyfftw_dask_interface.py", line 188, in validate
    self._validate(array_type, test_shape, dtype, s, kwargs)
  File "/home/travis/build/pyFFTW/pyFFTW/test/test_pyfftw_dask_interface.py", line 261, in _validate
    rtol=1e-2, atol=1e-4))
AssertionError: dask.array<all-aggregate, shape=(), dtype=bool, chunksize=(), chunktype=numpy.ndarray> is not true
```

Is what is like tripping it up.

**Comment by grlee77** [comment]
I also get FutureWarnings for dask 2.1 as well, so that part is not specifc to 2.8.  

```
Results (85.37s):
     103 passed
       4 failed
         - test/test_pyfftw_dask_interface.py:458 InterfacesDaskFFTTestRFFT.test_dtype_coercian
         - test/test_pyfftw_dask_interface.py:458 InterfacesDaskFFTTestRFFT2.test_dtype_coercian
         - test/test_pyfftw_dask_interface.py:458 InterfacesDaskFFTTestRFFTN.test_dtype_coercian
         - test/test_pyfftw_dask_interface.py:458 InterfacesDaskFFTTestIHFFT.test_dtype_coercian
```

```
E   AssertionError: <class 'FutureWarning'> is not <class 'numpy.ComplexWarning'>
```

**Comment by grlee77** [comment]
Hi @xnox, thanks for reporting this.
Please see if the changes proposed in #278 fix the issue for you.
