### ISSUE TITLE
Cannot assign type void (void) except * to void (*)(void) noexcept

### ISSUE THREAD

**Issue by carlosal1015** [pyFFTW/pyFFTW#362]
Hi, when we run `python setup.py build_ext --inplace` we have the following message with Python 3.11.3 and Cython version 3.0.0.

```python
Error compiling Cython file:
------------------------------------------------------------
...
IF HAVE_SINGLE_MULTITHREADING:
    fftwf_init_threads()
IF HAVE_LONG_MULTITHREADING:
    fftwl_init_threads()

Py_AtExit(_cleanup)
          ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:756:10: Cannot assign type 'void (void) except *' to 'void (*)(void) noexcept'
warning: pyfftw/pyfftw.pyx:414:22: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:420:22: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:425:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:430:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:437:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation

Error compiling Cython file:
------------------------------------------------------------
...

    # count the length of the string and extract it manually rather than using
    # `fftw_export_wisdom_to_string` to avoid calling `free` on the string
    # potentially allocated by a different C library; see #3
    IF HAVE_DOUBLE:
        fftw_export_wisdom(&count_char, <void *>&counter)
                           ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2053:27: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'

Error compiling Cython file:
------------------------------------------------------------
...
        c_wisdom = <char *>malloc(sizeof(char)*(counter + 1))
        if c_wisdom == NULL:
            raise MemoryError
        # Set the pointers to the string pointers
        cdef intptr_t c_wisdom_ptr = <intptr_t>c_wisdom
        fftw_export_wisdom(&write_char_to_string, <void *>&c_wisdom_ptr)
                           ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2059:27: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'

Error compiling Cython file:
------------------------------------------------------------
...
        try:
            py_wisdom = c_wisdom
        finally:
            free(c_wisdom)
    IF HAVE_SINGLE:
        fftwf_export_wisdom(&count_char, <void *>&counterf)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2067:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'

Error compiling Cython file:
------------------------------------------------------------
...
        fftwf_export_wisdom(&count_char, <void *>&counterf)
        c_wisdomf = <char *>malloc(sizeof(char)*(counterf + 1))
        if c_wisdomf == NULL:
            raise MemoryError
        cdef intptr_t c_wisdomf_ptr = <intptr_t>c_wisdomf
        fftwf_export_wisdom(&write_char_to_string, <void *>&c_wisdomf_ptr)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2072:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'

Error compiling Cython file:
------------------------------------------------------------
...
        try:
            py_wisdomf = c_wisdomf
        finally:
            free(c_wisdomf)
    IF HAVE_LONG:
        fftwl_export_wisdom(&count_char, <void *>&counterl)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2079:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'

Error compiling Cython file:
------------------------------------------------------------
...
        fftwl_export_wisdom(&count_char, <void *>&counterl)
        c_wisdoml = <char *>malloc(sizeof(char)*(counterl + 1))
        if c_wisdoml == NULL:
            raise MemoryError
        cdef intptr_t c_wisdoml_ptr = <intptr_t>c_wisdoml
        fftwl_export_wisdom(&write_char_to_string, <void *>&c_wisdoml_ptr)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2084:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'
Traceback (most recent call last):
  File "/tmp/pyFFTW/setup.py", line 835, in <module>
    setup_package()
  File "/tmp/pyFFTW/setup.py", line 827, in setup_package
    trial_distribution = setup(**setup_args)
                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/tmp/pyFFTW/setup.py", line 651, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
    new_ext = cythonize(
              ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pyfftw/pyfftw.pyx
```

**Comment by pranayj777** [comment]
@carlosal1015 Any update on this, I am getting the same error

**Comment by hgomersall** [comment]
PRs welcome on this - I suspect it's a fairly easy fix.

**Comment by hgomersall** [comment]
In the meantime, I suggest using cython < 3.

**Comment by hgomersall** [comment]
Here's the relevant migration docs: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept

**Comment by paugier** [comment]
I guess it is fixed.
